### PR TITLE
add link to rendered for mass spec

### PR DESCRIPTION
**Pull request by mblue9**

### CODE REVIEW

**Comment by mblue9** [comment]
I'll merge to have a look but please let me know if this is ok (or not) as I can do for the other tuts.

**Comment by almahmoud** [comment]
There is no automatic push right now, but if you want to add the text you think is best to each, that would be amazing, and I can then deploy it manually. But also since it's weekend, I completely understand if you don't want to deal with it

**Comment by mblue9** [comment]
ok I'll add them now

**Comment by mblue9** [comment]
have added here https://github.com/Bioconductor/workshop-contributions/pull/27

**Pull request merged**
